### ISSUE TITLE
Missing definition in paper for | G_j | on page 7

### ISSUE THREAD

**Issue by esvhd** [parrt/stratx#2]
Hi @parrt ,

Thank you for the beautiful paper. I noticed the definition for $\mid G_j \mid$ is missing on page 7 of the paper [link](https://arxiv.org/abs/1907.06698). 

This is the first line below equation (2) on page 7. Would you mind elaborating on this please? Is | G_j | just the number of items of G_j? 

Thanks again.

**Comment by parrt** [comment]
Thanks! @jdwilson4 and I had great time with this. Sorry for typo. It should be cardinality of the G_j group. :)

**Comment by esvhd** [comment]
Great, thanks!
