### ISSUE TITLE
Dependence on "sklearn"?

### ISSUE THREAD

**Issue by dragoljub** [parrt/stratx#4]
Currently stratx requires ```sklearn``` https://pypi.org/project/sklearn/ Which says it is depricated and not updated since 2015

Should this be ```scikit-learn``` ? https://pypi.org/project/scikit-learn/

**Comment by parrt** [comment]
ah! good point. i had no idea it was called something else. pushed 0.4.1. thanks.

**Comment by dragoljub** [comment]
Fantastic turnaround! Just pip-installed and its looking good. 👍
